const productos=[
    {
        id:1,
        nombre:"manzana",
        precio:2,
        img:"img/manzana.jpg"
    },
    {
        id:2,
        nombre:"kiwi",
        precio:5,
        img:"img/kiwi.jpg"
    },
    {
        id:3,
        nombre:"platano",
        precio:4,
        img:"img/kiwi.jpg",
    },
    {
        id:4,
        nombre:"mango",
        precio:10,
        img:"img/kiwi.jpg"
    },
]